name: gweiland
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  badges: ^3.1.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  get_it: ^7.6.4
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/icons/svgs/
    - assets/icons/pngs/

  fonts:
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/inter/Inter-Medium.ttf    
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf